### PR TITLE
Update config.yml

### PR DESCRIPTION
**Pull request by tboy1337**
fixed error

### CODE REVIEW

**Comment by tboy1337** [comment]
Also please enable discussions on this repo so feature requests will work @masterking32

**Comment by masterking32** [comment]
Just create fixed changes for the Example Module no need to do it for all modules.

**Comment by tboy1337** [comment]
I've set the url in the example module issue and discussion templates to `masterking32/YOUR_MODULE_HERE`, if you push that to all of the other modules it will break the issue and discussion forms @masterking32.

**Comment by masterking32** [comment]
Okay then, please stop creating pull requests before you check everything. Test and ensure that everything works and is 100% fixed before creating a PR. This kind of PR is not beneficial, and these types of updates cause unnecessary restarts of people’s modules. So, when you are 100% sure everything is fine, then create a PR. This way, you'll generate fewer notifications for us as well. You are making people stop watching the project because of too many commits and PRs. First, check everything in your repository, and once you are certain everything is ready, then create the PR.

Additionally, please don't create issues for everything. Just check your errors, and only create an issue if you are sure it’s a real problem and the project isn’t working because of it. You are generating too many issues, and it feels like you have a lot of them. I haven't even read carefully most of your issues because of that. Please only create issues when they are genuinely needed, not for everything.

**Pull request closed without merging**
